### ISSUE TITLE
Documents(SRS, SDD)

### ISSUE THREAD

**Issue by whisst** [whisst/World-Time#1]
- We have to improve our Software system requirement and system design definication.
- This project is the first time of us in software engineering so we get some trouble such as: donnot 
   understand some terminology of software engineering, lack of scopes, etc...

**Comment by dhnquang** [comment]
which part that u dont understand ?

**Comment by whisst** [comment]
The term of Data Modeling and Entity guys, can u help me?

**Comment by dhnquang** [comment]
Data modeling is a technique to document a software system using diagrams and symbols. It is used to represent communication of data.

**Comment by whisst** [comment]
oh! Nice! Thanks
