### ISSUE TITLE
How to update time every minutes?  AB#738a415

### ISSUE THREAD

**Issue by whisst** [whisst/World-Time#6]
How can we update time continuos with API? With currently function we have, the users have to rechoose the timezone to update time.

AB#738a415

**Comment by dhnquang** [comment]
you can try stream builder in dart. It's a widget that builds itself based on the latest snapshot of interaction with a stream

**Comment by dhnquang** [comment]
Widget rebuilding is scheduled by each interaction, using State.setState, but is otherwise decoupled from the timing of the stream.

**Comment by lthoangg** [comment]
You guys can check if the current time and the screen time are differed or not. Then replace now with cururent time.

**Comment by whisst** [comment]
Tks! I tried but it didn't work! :(( I think streambuilder is the answear

**Comment by whisst** [comment]
this issue is already solved! So i closed! Thanks for all
